'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../../frontend/carousel-motion.js'),'utf8');
function setup(reduced=false){let now=1000,id=0;const frames=new Map();const context=vm.createContext({window:{matchMedia:()=>({matches:reduced})},Date:{now:()=>now},getComputedStyle:el=>({direction:el.rtl?'rtl':'ltr',gap:'10'}),requestAnimationFrame:fn=>{frames.set(++id,fn);return id},cancelAnimationFrame:id=>frames.delete(id)});vm.runInContext(source,context);return {api:context.window.LFCarouselMotion,time:value=>now=value,advance:time=>{const batch=[...frames.values()];frames.clear();batch.forEach(fn=>fn(time))}}}
function rail(rtl=false){const handlers={};return {rtl,scrollWidth:600,clientWidth:200,scrollLeft:0,dataset:{},style:{setProperty(key,value){this[key]=value}},querySelector:()=>({getBoundingClientRect:()=>({width:190})}),addEventListener:(name,fn)=>handlers[name]=fn,handlers};}
test('rails move and wrap correctly in RTL and LTR using independent intervals',()=>{const env=setup(true),a=rail(true),b=rail();env.api.tick(a,{intervalSeconds:2,transition:'instant'});env.api.tick(b,{intervalSeconds:5,transition:'instant'});env.time(3001);env.api.tick(a,{intervalSeconds:2,transition:'instant'});env.api.tick(b,{intervalSeconds:5,transition:'instant'});assert.equal(a.scrollLeft,-200);assert.equal(b.scrollLeft,0);env.api.move(a,1,{transition:'instant'},true);assert.equal(a.scrollLeft,-400);env.api.move(a,1,{transition:'instant'},true);assert.equal(a.scrollLeft,0);env.api.move(b,1,{transition:'instant'});env.advance(0);env.advance(2000);assert.equal(b.scrollLeft,200)});
test('smooth movement finishes and touching one rail pauses only that rail',()=>{const env=setup(),a=rail(true),b=rail();env.api.bind(a);env.api.bind(b);env.api.move(a,1,{transition:'smooth'});env.advance(0);env.advance(2000);assert.equal(a.scrollLeft,-200);a.handlers.touchstart();env.api.tick(a,{intervalSeconds:2,transition:'instant'});env.api.tick(b,{intervalSeconds:2,transition:'instant'});env.time(3500);env.api.tick(a,{intervalSeconds:2,transition:'instant'});env.api.tick(b,{intervalSeconds:2,transition:'instant'});assert.equal(a.scrollLeft,-200);env.advance(0);env.advance(2000);assert.equal(b.scrollLeft,200)});
test('carousel settings validate and sold totals are absent from storefront cards',()=>{const {validateHomepageSettings}=require('../src/homepage-settings');const settings={top5:{intervalSeconds:4,transition:'smooth'},bestSellers:{intervalSeconds:8,transition:'fade'}};assert.deepEqual(validateHomepageSettings({feature_carousels:settings}).feature_carousels,settings);assert.throws(()=>validateHomepageSettings({feature_carousels:{...settings,top5:{intervalSeconds:0,transition:'smooth'}}}));const app=fs.readFileSync(path.join(__dirname,'../../frontend/app.js'),'utf8');const render=app.slice(app.indexOf('function renderFeatureSections()'),app.indexOf('function clearSearchAutofill',app.indexOf('function renderFeatureSections()')));assert.doesNotMatch(render,/soldCount|x\.qty|مباع/);assert.match(render,/best\.map\(x=>featureCardHtml\(x\.p\)\)/)});

test('every transition animates for two seconds',()=>{for(const transition of ['smooth','slide','fade','instant']){const env=setup(),el=rail();env.api.move(el,1,{transition});env.advance(0);env.advance(1000);assert.ok(el.scrollLeft>0&&el.scrollLeft<200);env.advance(2000);assert.equal(el.scrollLeft,200)}});
