'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const express=require('express');const {PGlite}=require('@electric-sql/pglite');
const {createOutfitRouter,selection,dayKey,readImage,measurements,measurementPrompt}=require('../src/naya-outfit');
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aWZkAAAAASUVORK5CYII=','base64');
test('selection and Palestine day boundary',()=>{assert.throws(()=>selection([{productId:1},{productId:1}]));assert.throws(()=>selection([]));assert.equal(dayKey(new Date('2026-07-01T20:59:00Z')),'2026-07-01');assert.equal(dayKey(new Date('2026-07-01T21:00:00Z')),'2026-07-02')});
test('remote images cannot make outbound requests',async()=>{await assert.rejects(readImage('https://example.com/x.png',{}),/ارفعي/)});
test('durable daily quota, failures, concurrency, budget and private image',async t=>{
 const pg=new PGlite();await pg.exec(`CREATE TABLE products(id BIGINT PRIMARY KEY,name TEXT,image_url TEXT,image TEXT,is_active BOOLEAN);CREATE TABLE product_images(id BIGINT,product_id BIGINT,image_url TEXT,is_primary BOOLEAN,sort_order INT);CREATE TABLE uploaded_images(id TEXT,data BYTEA);CREATE TABLE naya_outfit_daily(user_id BIGINT,usage_day DATE,state TEXT,job_id UUID,selection JSONB,image BYTEA,error_message TEXT,updated_at TIMESTAMPTZ,PRIMARY KEY(user_id,usage_day));CREATE TABLE naya_outfit_budget(month TEXT PRIMARY KEY,attempts INT);INSERT INTO products VALUES(1,'Dress','/api/images/test',NULL,true);`);await pg.query('INSERT INTO uploaded_images VALUES($1,$2)',['test',png]);
 let calls=0,release,fail=false;const env={NAYA_OUTFIT_ENABLED:'true',OPENAI_API_KEY:'test',NAYA_OUTFIT_MONTHLY_LIMIT:'3'};
 const app=express();app.use(express.json());app.use('/api/ai/outfit',createOutfitRouter({db:(s,p)=>pg.query(s,p),transaction:fn=>pg.transaction(fn),requireAuth:(req,res,next)=>{const id=Number(req.headers['x-user']);if(!id)return res.sendStatus(401);req.user={id};next()},env,fetchImpl:async()=>{calls++;await new Promise(r=>release=r);return{ok:!fail,json:async()=>({data:[{b64_json:png.toString('base64')}]})}}}));app.use((e,req,res,next)=>(console.error(e),res.status(500).json({error:e.message})));
 const server=app.listen(0);await new Promise(r=>server.once('listening',r));t.after(async()=>{await new Promise(r=>server.close(r));await pg.close()});const base='http://127.0.0.1:'+server.address().port+'/api/ai/outfit';
 const request=(route,user=1,body)=>fetch(base+route,{method:body?'POST':'GET',headers:{'Content-Type':'application/json','x-user':String(user)},body:body?JSON.stringify(body):undefined});const generate=user=>request('/generate',user,{items:[{productId:1}]});
 async function waitState(user,state){for(let i=0;i<100;i++){const d=await(await request('/status',user)).json();if(d.state===state)return d;await new Promise(r=>setTimeout(r,10))}throw Error('state not reached: '+state)}
 assert.equal((await request('/status',0)).status,401);env.NAYA_OUTFIT_ENABLED='false';assert.equal((await generate(1)).status,503);assert.equal(calls,0);env.NAYA_OUTFIT_ENABLED='true';
 assert.equal((await request('/generate',1,{items:[{productId:1},{productId:1}]})).status,400);assert.equal((await request('/generate',1,{items:[{productId:1}],measurements:{height:165}})).status,400);assert.equal(calls,0);
 const responses=await Promise.all([generate(1),generate(1)]);assert.deepEqual(responses.map(r=>r.status).sort(),[202,409]);assert.equal(calls,1);release();await waitState(1,'complete');assert.equal((await generate(1)).status,409);assert.equal((await request('/image')).status,200);assert.equal((await request('/image',2)).status,404);
 fail=true;assert.equal((await generate(2)).status,202);release();assert.equal((await waitState(2,'failed')).remaining,1);fail=false;assert.equal((await generate(2)).status,202);release();await waitState(2,'complete');assert.equal(calls,3);assert.equal((await generate(3)).status,400);assert.equal(calls,3);assert.equal((await request('/status',3).then(r=>r.json())).remaining,1);
});

test('measurements require explicit consent, validate bounds and discard extra fields',()=>{assert.equal(measurements({}),null);assert.throws(()=>measurements({measurements:{height:165}}),/موافقتك/);assert.throws(()=>measurements({measurementsConsent:true,measurements:{height:300}}),/المقاسات/);const m=measurements({measurementsConsent:true,measurements:{height:165,weight:70,waist:80,secret:'ignore'}});assert.deepEqual(m,{height:165,weight:70,waist:80});assert.match(measurementPrompt(m),/165/);assert.equal(measurementPrompt(null),'')});
