'use strict';
const {test,before,after}=require('node:test'),assert=require('node:assert/strict'),{PGlite}=require('@electric-sql/pglite');
const database=new PGlite();process.env.JWT_SECRET='isolated-staff-activity-tests';
require.cache[require.resolve('../src/db')]={exports:{db:(sql,v)=>database.query(sql,v),transaction:fn=>database.transaction(tx=>fn({query:(sql,v)=>tx.query(sql,v)})),getDatabaseStatus:async()=>({configured:true,connected:true}),closeDatabase:async()=>{}}};
const {app,initDatabase}=require('../src/server'),{createToken}=require('../src/auth');let server,base;
before(async()=>{await initDatabase();await database.query(`INSERT INTO users(id,name,password_hash,role,permissions) VALUES(1,'Owner','fixture','owner','[]'),(2,'Packing employee','fixture','staff','["orders"]'),(3,'Report employee','fixture','staff','["reports"]'),(4,'Customer','fixture','customer','[]')`);await database.query("INSERT INTO orders(id,status) VALUES(1,'processing'),(2,'cancelled'),(3,'delivered')");server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));base='http://127.0.0.1:'+server.address().port});
after(async()=>{await new Promise(r=>server.close(r));await database.close()});
async function request(url,id,body){return fetch(base+url,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',Authorization:'Bearer '+createToken({id,role:id===1?'owner':id===4?'customer':'staff'})},...(body?{body:JSON.stringify(body)}:{})})}
test('preparation uses authenticated employee identity, persists a snapshot and cannot be reassigned',async()=>{assert.equal((await request('/api/admin/orders/1/preparation',4,{})).status,403);assert.equal((await request('/api/admin/orders/1/preparation',3,{})).status,403);const response=await request('/api/admin/orders/1/preparation',2,{prepared_by:1,prepared_by_name:'Spoofed'});assert.equal(response.status,200);const order=(await response.json()).order;assert.equal(Number(order.prepared_by),2);assert.equal(order.prepared_by_name,'Packing employee');assert.ok(order.prepared_at);assert.equal((await request('/api/admin/orders/1/preparation',2,{})).status,200);assert.equal((await request('/api/admin/orders/1/preparation',1,{})).status,409);await database.query("UPDATE users SET name='Renamed employee' WHERE id=2");const details=await (await request('/api/admin/orders/1',1)).json();assert.equal(details.order.prepared_by_name,'Packing employee');assert.equal((await request('/api/admin/orders/2/preparation',2,{})).status,409);assert.equal((await request('/api/admin/orders/3/preparation',2,{})).status,409)});
test('activity report is permission protected, date filtered and records real actors without request secrets',async()=>{for(let i=0;i<10;i++){const result=await database.query('SELECT COUNT(*)::int AS n FROM staff_activity_log');if(result.rows[0].n>=5)break;await new Promise(r=>setTimeout(r,10))}const range='?from=2020-01-01&to=2030-01-01&employee=2';assert.equal((await request('/api/admin/reports/staff-activity'+range,2)).status,403);const response=await request('/api/admin/reports/staff-activity'+range,3);assert.equal(response.status,200);const data=await response.json();assert.ok(data.rows.length>=3);assert.ok(data.rows.every(x=>Number(x.actor_id)===2));assert.ok(data.rows.some(x=>x.actor_name==='Packing employee'&&x.status_code===200));assert.ok(data.rows.some(x=>x.status_code===409));assert.ok(!JSON.stringify(data).includes('Spoofed'));const empty=await (await request('/api/admin/reports/staff-activity?from=2020-01-01&to=2020-01-02',1)).json();assert.equal(empty.total,0);assert.equal((await request('/api/admin/reports/staff-activity?from=invalid&to=invalid',1)).status,400)});
test('invoice prints the recorded preparer and order details provide an explicit preparation action',()=>{const source=require('node:fs').readFileSync(require('node:path').join(__dirname,'../../frontend/admin.js'),'utf8');assert.match(source,/invoicePreparedBy/);assert.match(source,/E\(o.prepared_by_name\|\|'لم يُسجّل بعد'\)/);assert.match(source,/أنا جهّزت الطلبية/)});
