const $=s=>document.querySelector(s),E=v=>String(v??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x])),M=v=>Number(v||0).toFixed(2);let sec='dashboard';
async function api(u,o={}){const token=localStorage.getItem('lf_admin_token')||'';const headers={'Content-Type':'application/json',...(o.headers||{})};if(token)headers.Authorization='Bearer '+token;let r=await fetch(u,{...o,headers}),d={};try{d=await r.json()}catch{}if(r.status===401){localStorage.removeItem('lf_admin_token');showLogin();throw Error(d.message||'انتهت جلسة الدخول')}if(!r.ok||d.ok===false)throw Error(d.message||('HTTP '+r.status));return d}

function showLogin(){const l=$('#login'),a=$('#app');if(l)l.hidden=false;if(a)a.hidden=true;const b=$('#recoveryBox');if(b)b.hidden=true}
async function showApp(){const l=$('#login'),a=$('#app');if(l)l.hidden=true;if(a)a.hidden=false;try{const d=await api('/api/auth/me');if(!d.user||!['owner','admin','staff'].includes(String(d.user.role||'').toLowerCase())){localStorage.removeItem('lf_admin_token');showLogin();$('#loginMsg').textContent='جلسة الإدارة غير صالحة أو الحساب غير مفعل.';return}await load()}catch(e){if(a)a.hidden=true;if(l)l.hidden=false;const msg=e&&e.message?e.message:'تعذر التحقق من جلسة الدخول';$('#loginMsg').textContent=msg.includes('جلسة')||msg.includes('انتهت')?msg:'تعذر فتح لوحة التحكم: '+msg}}
async function adminLogin(){const contact=$('#loginContact').value.trim(),password=$('#loginPassword').value||'',msg=$('#loginMsg');if(!contact||!password){msg.textContent='أدخل البريد أو الهاتف وكلمة المرور';return}try{const d=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contact,password})});const x=await d.json();if(!d.ok||x.ok===false)throw Error(x.message||'بيانات الدخول غير صحيحة');if(!['owner','admin','staff'].includes(String(x.user?.role||'').toLowerCase()))throw Error('هذا الحساب ليس حساب إدارة');localStorage.setItem('lf_admin_token',x.token);showApp()}catch(e){msg.textContent=e.message}}
async function logout(){try{await fetch('/api/auth/logout',{method:'POST'});}catch{}localStorage.removeItem('lf_admin_token');showLogin()}
function showRecovery(){const b=$('#recoveryBox');b.hidden=false;b.innerHTML='<h3>استرداد كلمة المرور</h3><p class="small-note">أدخل الإيميل أو رقم الهاتف. سيصلك رمز صالح لمدة 15 دقيقة.</p><input id="rc" class="field" placeholder="البريد الإلكتروني أو الهاتف" autocomplete="username"><button class="btn" onclick="requestRecovery()">إرسال رمز الاسترداد</button><div id="recoveryConfirm" style="margin-top:10px"></div>'}
async function requestRecovery(){const contact=$('#rc').value.trim();if(!contact)return;try{const d=await fetch('/api/auth/password-recovery/request',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contact})});const x=await d.json();if(!d.ok||x.ok===false)throw Error(x.message||'تعذر إرسال الرمز');$('#recoveryConfirm').innerHTML='<input id="rCode" class="field" inputmode="numeric" maxlength="6" placeholder="رمز الاسترداد"><input id="rNew" class="field" type="password" minlength="12" placeholder="كلمة المرور الجديدة — 12 خانة على الأقل"><button class="btn primary" onclick="confirmRecovery()">تأكيد وتغيير كلمة المرور</button>';$('#loginMsg').textContent=x.message}catch(e){$('#loginMsg').textContent=e.message}}
async function confirmRecovery(){const contact=$('#rc').value.trim(),code=$('#rCode').value.trim(),newPassword=$('#rNew').value;if(newPassword.length<12){$('#loginMsg').textContent='كلمة المرور الجديدة يجب أن تكون 12 خانة على الأقل';return}try{const d=await fetch('/api/auth/password-recovery/confirm',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contact,code,newPassword})});const x=await d.json();if(!d.ok||x.ok===false)throw Error(x.message||'تعذر تغيير كلمة المرور');$('#loginMsg').textContent='تم تغيير كلمة المرور. يمكنك تسجيل الدخول الآن.';$('#recoveryBox').hidden=true}catch(e){$('#loginMsg').textContent=e.message}}
function showOwnerSetup(){const b=$('#recoveryBox');b.hidden=false;b.innerHTML='<h3>إعداد المالك لأول مرة</h3><p class="small-note">هذا الخيار يعمل مرة واحدة فقط، ومقيد بالإيميل والهاتف المعتمدين في النظام.</p><input id="osName" class="field" value="Khaled" placeholder="اسم المالك"><input id="osEmail" class="field" value="khaledawwad21@gmail.com" readonly><input id="osPhone" class="field" value="0562499924" readonly><input id="osPass" class="field" type="password" minlength="12" placeholder="اختر كلمة مرور — 12 خانة على الأقل"><button class="btn primary" onclick="bootstrapOwner()">إنشاء حساب المالك</button>'}
async function bootstrapOwner(){const password=$('#osPass').value;if(password.length<12){$('#loginMsg').textContent='كلمة المرور يجب أن تكون 12 خانة على الأقل';return}try{const d=await fetch('/api/auth/bootstrap-owner',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('#osName').value.trim(),email:$('#osEmail').value,phone:$('#osPhone').value,password})});const x=await d.json();if(!d.ok||x.ok===false)throw Error((x.code?x.code+' — ':'')+(x.message||'تعذر إنشاء حساب المالك'));localStorage.setItem('lf_admin_token',x.token);showApp()}catch(e){$('#loginMsg').textContent=e.message}}
async function changeOwnPassword(){const current=$('#cpCurrent')?.value||'',next=$('#cpNew')?.value||'';if(next.length<12)return alert('كلمة المرور الجديدة يجب أن تكون 12 خانة على الأقل');try{await api('/api/auth/password',{method:'PATCH',body:JSON.stringify({currentPassword:current,newPassword:next})});alert('تم تغيير كلمة المرور بنجاح');$('#cpCurrent').value='';$('#cpNew').value=''}catch(e){alert(e.message)}}

function toast(x){let t=$('#toast');t.textContent=x;t.style.cssText='display:block;position:fixed;bottom:18px;left:18px;background:#63345e;color:white;padding:12px 16px;border-radius:10px;z-index:20';setTimeout(()=>t.style.display='none',2500)}
const titles={dashboard:'الرئيسية',users:'المستخدمون',products:'المنتجات',inventory:'المخزون',orders:'الطلبات والفواتير',finance:'الحسابات',offers:'العروض والحملات',catalog:'التصنيفات والعلامات',coupons:'الكوبونات',reports:'التقارير',homepage:'الصفحة الرئيسية',social:'مواقع التواصل',settings:'الإعدادات',staff:'الموظفون والصلاحيات'};
const navs=[...document.querySelectorAll('.nav')];navs.forEach(n=>n.onclick=()=>{sec=n.dataset.s;navs.forEach(x=>x.classList.toggle('active',x===n));$('#title').textContent=titles[sec];load()});
function table(h,rows){return rows.length?`<div class="tablewrap"><table class="table"><thead><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`:'<p>لا توجد بيانات.</p>'}
async function load(){try{if(sec==='dashboard')return dash();if(sec==='users')return users();if(sec==='products')return products();if(sec==='inventory')return inventory();if(sec==='orders')return orders();if(sec==='finance')return finance();if(sec==='catalog')return catalog();if(sec==='coupons')return coupons();if(sec==='reports')return reports();if(sec==='social')return social();if(sec==='settings')return settings();if(sec==='staff')return staff();if(sec==='offers')return offers();if(sec==='homepage')return homepage()}catch(e){toast(e.message)}}
async function dash(){let d=await api('/api/admin/dashboard'),x=d.dashboard;$('#sections').innerHTML=`<div class="cards">${[['العملاء',x.customers],['المنتجات',x.products],['الطلبات',x.orders],['المبيعات',M(x.sales)],['قيد التنفيذ',x.pendingOrders],['مخزون منخفض',x.lowStock]].map(a=>`<div class="stat"><small>${a[0]}</small><b>${a[1]}</b></div>`).join('')}</div><div class="grid"><div class="card"><h2>تنبيهات</h2>${x.lowStock?`يوجد ${x.lowStock} منتج منخفض المخزون.`:'لا يوجد تنبيه مخزون ضمن الحد الحالي.'}</div><div class="card"><h2>ملاحظة</h2>هذه الواجهة مرتبطة بالـAPI الموجود حاليًا ولن تغيّر بيانات الموقع بدون طلب صريح.</div></div>`}
async function users(){let q=encodeURIComponent($('#uq')?.value||''),d=await api('/api/admin/users?search='+q);$('#sections').innerHTML=`<div class="card"><h2>المستخدمون</h2><div class="toolbar"><input id="uq" class="field" placeholder="بحث بالاسم أو البريد أو الهاتف" value="${E(decodeURIComponent(q))}"><button class="btn primary" onclick="users()">بحث</button></div>${table(['الاسم','البريد','الهاتف','الجنس','العمر','الدور','الحالة',''],(d.users||[]).map(u=>`<tr><td>${E(u.name)}</td><td>${E(u.email)}</td><td>${E(u.phone||'-')}</td><td>${E(u.gender||'-')}</td><td>${u.age||'-'}</td><td>${E(u.role)}</td><td>${u.is_active?'فعال':'متوقف'}</td><td><button class="btn" onclick='editUser(${JSON.stringify(u)})'>تعديل</button></td></tr>`))}</div>`}
function editUser(u){modal('تعديل المستخدم',`<div class="formgrid"><input id="un" class="field" value="${E(u.name)}" placeholder="الاسم"><input id="ue" class="field" value="${E(u.email)}" placeholder="البريد"><input id="up" class="field" value="${E(u.phone||'')}" placeholder="الهاتف"><select id="ug" class="field"><option value="">غير محدد</option><option value="male" ${u.gender==='male'?'selected':''}>ذكر</option><option value="female" ${u.gender==='female'?'selected':''}>أنثى</option></select><input id="ua" class="field" type="number" value="${u.age||''}" placeholder="العمر"></div><div class="actions"><button class="btn primary" onclick="saveUser(${u.id})">حفظ</button></div>`)}
async function saveUser(id){await api('/api/admin/users/'+id,{method:'PATCH',body:JSON.stringify({name:$('#un').value,email:$('#ue').value,phone:$('#up').value,gender:$('#ug').value||null,age:$('#ua').value?Number($('#ua').value):null})});closeModal();toast('تم الحفظ');users()}
async function products(){let d=await api('/api/products');$('#sections').innerHTML=`<div class="card"><h2>المنتجات</h2><div class="toolbar"><input id="pq" class="field" placeholder="بحث"><button class="btn" onclick="productForm()">+ منتج جديد</button></div>${table(['المنتج','السعر','المخزون','الحالة',''],(d.products||[]).filter(p=>(p.name||'').includes($('#pq')?.value||'')).map(p=>`<tr><td>${E(p.name)}</td><td>${M(p.price)}</td><td>${p.stock??0}</td><td>${p.is_active?'فعال':'متوقف'}</td><td><button class="btn" onclick='productForm(${JSON.stringify(p)})'>تعديل</button></td></tr>`))}</div>`}
function productForm(p={}){modal(p.id?'تعديل المنتج':'منتج جديد',`<div class="formgrid"><input id="pn" class="field" value="${E(p.name||'')}" placeholder="اسم المنتج"><input id="pp" class="field" type="number" step=".01" value="${p.price??''}" placeholder="السعر"><input id="po" class="field" type="number" step=".01" value="${p.old_price??''}" placeholder="السعر القديم"><input id="ps" class="field" type="number" value="${p.stock??0}" placeholder="المخزون"><input id="pi" class="field full" value="${E(p.image_url||'')}" placeholder="رابط الصورة"><textarea id="pd" class="field full" rows="5" placeholder="الوصف">${E(p.description||'')}</textarea><div class="full">الفيديوهات ستُفعّل بعد إضافة حقول/Endpoint الفيديو إلى الـBackend؛ لن يتم تخزين بيانات غير مدعومة.</div></div><div class="actions"><button class="btn primary" onclick="saveProduct(${p.id||0})">حفظ</button></div>`)}
async function saveProduct(id){let b={name:$('#pn').value,price:Number($('#pp').value),oldPrice:$('#po').value?Number($('#po').value):null,stock:Number($('#ps').value),imageUrl:$('#pi').value,description:$('#pd').value};await api(id?'/api/admin/products/'+id:'/api/admin/products',{method:id?'PUT':'POST',body:JSON.stringify(b)});closeModal();toast('تم حفظ المنتج');products()}
async function inventory(){let d=await api('/api/admin/inventory'),p=d.products||[];$('#sections').innerHTML=`<div class="card"><h2>المخزون</h2><button class="btn" onclick="inventoryMovements()">تقرير حركات المخزون</button>${table(['المنتج','SKU','الكمية','السعر','التصنيف',''],p.map(x=>`<tr><td>${E(x.name)}</td><td>${E(x.sku||'-')}</td><td>${x.stock??0}</td><td>${M(x.price)}</td><td>${E(x.category_name||'-')}</td><td><button class="btn" onclick="stock(${x.id},${x.stock||0})">تعديل</button></td></tr>`))}</div>`}
let movementRequest = 0;
function inventoryMovements(){
  movementRequest++;
  $('#sections').innerHTML=`<div class="card"><h2>تقرير حركات المخزون</h2><button class="btn" onclick="inventory()">العودة للمخزون</button><div class="toolbar"><label>من <input id="mf" type="date" class="field" onchange="movementRun()"></label><label>إلى <input id="mtDate" type="date" class="field" onchange="movementRun()"></label></div><div id="movementRows" aria-live="polite">اختاري تاريخ البداية والنهاية لعرض الحركات.</div></div>`;
}
function movementReason(reason){
  const names={order_cancel_return:'إرجاع مخزون طلب ملغى',customer_return:'إرجاع من العميل',customer_exchange_return:'استبدال: إعادة القطعة',customer_exchange_out:'استبدال: صرف القطعة البديلة'};
  return names[reason]||(String(reason||'').startsWith('sale:')?'بيع: '+String(reason).slice(5).trim():reason||'-');
}
async function movementRun(){
  const request=++movementRequest, target=$('#movementRows'), from=$('#mf')?.value, to=$('#mtDate')?.value;
  if(!target)return;
  if(!from||!to){target.textContent='اختاري تاريخ البداية والنهاية لعرض الحركات.';return}
  if(from>to){target.textContent='تاريخ البداية يجب أن يكون قبل النهاية أو مساوياً لها.';return}
  target.textContent='جاري تحميل الحركات…';
  try{
    const d=await api('/api/admin/inventory/movements?'+new URLSearchParams({from,to}));
    if(request!==movementRequest||$('#movementRows')!==target)return;
    target.innerHTML=table(['التاريخ','المنتج','اللون / المقاس','SKU','تغير الكمية','السبب','رقم الطلب'],(d.movements||[]).map(x=>`<tr><td>${E(new Date(x.created_at).toLocaleString('ar'))}</td><td>${E(x.product_name||'منتج محذوف')}</td><td>${E([x.color,x.size].filter(Boolean).join(' / ')||'-')}</td><td>${E(x.variant_sku||'-')}</td><td>${Number(x.quantity_change)>0?'+':''}${E(x.quantity_change)}</td><td>${E(movementReason(x.reason))}</td><td>${x.order_id?'#'+E(x.order_id):'-'}</td></tr>`));
  }catch(e){if(request===movementRequest&&$('#movementRows')===target)target.textContent=e.message}
}
function stock(id,n){modal('تعديل المخزون',`<input id="sn" class="field" type="number" min="0" value="${n}"><div class="actions"><button class="btn primary" onclick="saveStock(${id})">حفظ</button></div>`)}async function saveStock(id){await api('/api/admin/inventory/'+id,{method:'PATCH',body:JSON.stringify({stock:Number($('#sn').value)})});closeModal();toast('تم تحديث المخزون');inventory()}
async function orders(){let d=await api('/api/admin/orders');$('#sections').innerHTML=`<div class="card"><h2>الطلبات والفواتير</h2>${table(['رقم','العميل','الهاتف','الإجمالي','الحالة','التاريخ',''],(d.orders||[]).map(o=>`<tr><td>#${o.id}</td><td>${E(o.user_name||o.user_email||'-')}</td><td>${E(o.user_phone||'-')}</td><td>${M(o.total)}</td><td>${E(o.status)}</td><td>${new Date(o.created_at).toLocaleString('ar')}</td><td><button class="btn" onclick="invoice(${o.id})">عرض/طباعة</button></td></tr>`))}</div>`}
async function invoice(id){let d=await api('/api/admin/orders/'+id),o=d.order,items=d.items||[];let site=location.origin,orderUrl=site+'/order/'+id;let payment=String(o.payment_method||'cash').toLowerCase()==='visa'?'Visa':'الدفع عند الاستلام';let region={westbank:'الضفة',jerusalem:'القدس',inside:'الداخل'}[String(o.shipping_region||'').toLowerCase()]||o.shipping_region||'-';let shipping=o.shipping_waived?'معفى':M(o.shipping_cost||0);$('#print').innerHTML=`<div class="printhead"><h1>Ladies First</h1><div>فاتورة #${id}<br>${new Date(o.created_at).toLocaleString('ar')}</div></div><p>العميل: ${E(o.user_name||o.customer_name||'-')}<br>الهاتف: ${E(o.user_phone||o.customer_phone||'-')}<br>البريد: ${E(o.user_email||'-')}<br>العنوان: ${E(o.shipping_address||'-')}<br>منطقة التوصيل: ${E(region)}<br>طريقة الدفع: ${E(payment)}</p>${table(['المنتج','الخيار','الكمية','السعر','الإجمالي'],items.map(i=>`<tr><td>${E(i.product_name||'-')}</td><td>${E(i.variant_name||'-')}</td><td>${i.quantity}</td><td>${M(i.unit_price)}</td><td>${M(i.total)}</td></tr>`))}<div class="invoiceTotals"><p>المجموع الفرعي: <b>${M(o.subtotal||0)}</b></p><p>خصم الكوبون${o.coupon_code?' ('+E(o.coupon_code)+')':''}: <b>-${M(o.coupon_discount||0)}</b></p><p>خصم Visa: <b>-${M(o.visa_discount||0)}</b></p><p>خصم نقاط الولاء${Number(o.points_redeemed||0)>0?' ('+Number(o.points_redeemed)+' نقطة)':''}: <b>-${M(o.loyalty_discount||0)}</b></p><p>التغليف: <b>${M(o.packaging_cost||0)}</b></p><p>التوصيل (${E(region)}): <b>${shipping}</b></p><p><b>الإجمالي النهائي: ${M(o.total)}</b></p></div><div class="qrrow"><div><div id="qrsite"></div><b>زوروا موقعنا</b></div><div><div id="qrorder"></div><b>تفاصيل طلبك</b></div></div>`;new QRCode($('#qrsite'),{text:site,width:145,height:145});new QRCode($('#qrorder'),{text:orderUrl,width:145,height:145});window.print()}
function invoicePrompt(){let id=prompt('أدخل رقم الطلب');if(id)invoice(Number(id))}async function finance(){let d=await api('/api/admin/dashboard');$('#sections').innerHTML=`<div class="grid"><div class="card"><h2>الحسابات الحالية</h2><p>إجمالي المبيعات المسجلة: <b>${M(d.dashboard.sales)}</b></p><p>الطلبات: <b>${d.dashboard.orders}</b></p></div><div class="card"><h2>تنبيه محاسبي</h2>صافي الربح الحقيقي يحتاج ربط تكلفة الشراء والمصاريف والمرتجعات في طبقة الحسابات قبل اعتماده محاسبيًا.</div></div>`}
async function catalog(){let[c,b]=await Promise.all([api('/api/categories'),api('/api/brands')]);$('#sections').innerHTML=`<div class="grid"><div class="card"><h2>التصنيفات</h2><div class="toolbar"><input id="cn" class="field"><button class="btn primary" onclick="addCat()">إضافة</button></div>${table(['الاسم'],(c.categories||[]).map(x=>`<tr><td>${E(x.name)}</td></tr>`))}</div><div class="card"><h2>العلامات</h2><div class="toolbar"><input id="bn" class="field"><button class="btn primary" onclick="addBrand()">إضافة</button></div>${table(['الاسم'],(b.brands||[]).map(x=>`<tr><td>${E(x.name)}</td></tr>`))}</div></div>`}async function addCat(){await api('/api/admin/categories',{method:'POST',body:JSON.stringify({name:$('#cn').value})});catalog()}async function addBrand(){await api('/api/admin/brands',{method:'POST',body:JSON.stringify({name:$('#bn').value})});catalog()}
async function coupons(){let d=await api('/api/admin/coupons');$('#sections').innerHTML=`<div class="card"><h2>الكوبونات</h2><button class="btn primary" onclick="couponForm()">+ كوبون</button>${table(['الكود','النوع','القيمة','الحالة'],(d.coupons||[]).map(x=>`<tr><td>${E(x.code)}</td><td>${E(x.discount_type)}</td><td>${x.discount_value}</td><td>${x.is_active?'فعال':'متوقف'}</td></tr>`))}</div>`}function couponForm(){modal('كوبون جديد',`<div class="formgrid"><input id="cc" class="field" placeholder="الكود"><select id="ct" class="field"><option value="percent">نسبة</option><option value="fixed">مبلغ</option></select><input id="cv" class="field" type="number" step=".01" placeholder="القيمة"><input id="cm" class="field" type="number" step=".01" placeholder="الحد الأدنى"><input id="cx" class="field" type="number" placeholder="أقصى استخدامات"></div><div class="actions"><button class="btn primary" onclick="saveCoupon()">حفظ</button></div>`)}async function saveCoupon(){await api('/api/admin/coupons',{method:'POST',body:JSON.stringify({code:$('#cc').value,discountType:$('#ct').value,discountValue:Number($('#cv').value),minimumAmount:Number($('#cm').value||0),maxUses:Number($('#cx').value||0)})});closeModal();coupons()}
async function reports(){let t=new Date().toISOString().slice(0,10);$('#sections').innerHTML=`<div class="card"><h2>تقارير المبيعات والأرباح</h2><div class="toolbar"><input id="rf" type="date" class="field" value="${t}" onchange="reportRun()"><input id="rt" type="date" class="field" value="${t}" onchange="reportRun()"></div><div id="rr"></div></div>`;reportRun()}async function reportRun(){let d=await api('/api/admin/reports/sales?from='+$('#rf').value+'&to='+$('#rt').value),s=d.summary||{};$('#rr').innerHTML=`<div class="cards"><div class="stat">الطلبات<b>${s.orders||0}</b></div><div class="stat">المبيعات<b>${M(s.sales)}</b></div><div class="stat">التكلفة<b>${M(s.cost)}</b></div><div class="stat">الربح<b>${M(s.profit)}</b></div><div class="stat">الملغاة<b>${s.cancelled||0}</b></div></div>`+table(['التاريخ','الطلبات','المبيعات','التكلفة','الربح'],(d.rows||[]).map(x=>`<tr><td>${x.date}</td><td>${x.orders}</td><td>${M(x.sales)}</td><td>${M(x.cost)}</td><td>${M(x.profit)}</td></tr>`))}
async function settings(){let d=await api('/api/admin/settings'),s=d.settings||{};$('#sections').innerHTML=`<div class="grid"><div class="card"><h2>الإعدادات</h2><div class="formgrid"><input id="stn" class="field" value="${E(s.store_name||'Ladies First')}" placeholder="اسم المتجر"><input id="stp" class="field" value="${E(s.phone||'')}" placeholder="الهاتف"><input id="stw" class="field" value="${E(s.whatsapp||'0562499924')}" placeholder="WhatsApp"><input id="cur" class="field" value="${E(s.currency||'₪')}" placeholder="العملة"><textarea id="rp" class="field full" rows="5" placeholder="سياسة الاستبدال">${E(s.return_policy||'')}</textarea></div><div class="actions"><button class="btn primary" onclick="saveSettings()">حفظ</button></div></div><div class="card"><h2>أمان الحساب</h2><p>تغيير كلمة المرور يتطلب كلمة المرور الحالية. الحد الأدنى 12 خانة.</p><div class="formgrid"><input id="cpCurrent" class="field" type="password" placeholder="كلمة المرور الحالية"><input id="cpNew" class="field" type="password" minlength="12" placeholder="كلمة المرور الجديدة"></div><div class="actions"><button class="btn primary" onclick="changeOwnPassword()">تغيير كلمة المرور</button></div></div></div>`}async function saveSettings(){await api('/api/admin/settings',{method:'PUT',body:JSON.stringify({store_name:$('#stn').value,phone:$('#stp').value,whatsapp:$('#stw').value,currency:$('#cur').value,return_policy:$('#rp').value})});toast('تم حفظ الإعدادات')}
async function social(){let d=await api('/api/admin/settings'),s=d.settings?.social||{};$('#sections').innerHTML=`<div class="card"><h2>مواقع التواصل</h2>${['whatsapp','instagram','snapchat','facebook','tiktok'].map(k=>`<div class="toolbar"><input id="s_${k}" class="field" value="${E(s[k]?.url||s[k]||'')}" placeholder="${k} URL"><label><input id="e_${k}" type="checkbox" ${s[k]?.enabled===false?'':'checked'}> فعال</label></div>`).join('')}<button class="btn primary" onclick="saveSocial()">حفظ</button></div>`}async function saveSocial(){let social={};['whatsapp','instagram','snapchat','facebook','tiktok'].forEach(k=>social[k]={url:$('#s_'+k).value,enabled:$('#e_'+k).checked});await api('/api/admin/settings',{method:'PUT',body:JSON.stringify({social})});toast('تم حفظ مواقع التواصل')}
async function staff(){let d=await api('/api/admin/staff');$('#sections').innerHTML=`<div class="card"><h2>الموظفون والصلاحيات</h2><button class="btn primary" onclick="staffForm()">+ موظف</button>${table(['الاسم','البريد','الهاتف','الدور','الحالة'],(d.staff||[]).map(x=>`<tr><td>${E(x.name)}</td><td>${E(x.email)}</td><td>${E(x.phone||'-')}</td><td>${E(x.role)}</td><td>${x.is_active?'فعال':'متوقف'}</td></tr>`))}</div>`}function staffForm(){modal('موظف جديد',`<div class="formgrid"><input id="sn" class="field" placeholder="الاسم"><input id="se" class="field" placeholder="البريد"><input id="sp" class="field" placeholder="الهاتف"><input id="sw" class="field" type="password" placeholder="كلمة المرور"><select id="sr" class="field"><option value="staff">staff</option><option value="admin">admin</option></select></div><div class="actions"><button class="btn primary" onclick="saveStaff()">حفظ</button></div>`)}async function saveStaff(){await api('/api/admin/staff',{method:'POST',body:JSON.stringify({name:$('#sn').value,email:$('#se').value,phone:$('#sp').value,password:$('#sw').value,role:$('#sr').value})});closeModal();staff()}
function offers(){$('#sections').innerHTML='<div class="card"><h2>العروض والحملات</h2><p>واجهة إعداد الحملة موجودة هنا. الإرسال الجماعي عبر WhatsApp يحتاج ربط WhatsApp Business/API في الـBackend قبل تشغيله فعليًا.</p><div class="formgrid"><input id="ot" class="field" placeholder="عنوان العرض"><input id="ol" class="field" placeholder="رابط العرض"><textarea id="om" class="field full" rows="5" placeholder="رسالة الحملة"></textarea></div></div>'}function homepage(){$('#sections').innerHTML='<div class="card"><h2>الصفحة الرئيسية</h2><p>إدارة البنرات والمحتوى وTop 5 والأكثر مبيعًا تحتاج ربط مخطط المحتوى الفعلي الموجود في قاعدة البيانات، ولن أضيف تخزينًا وهميًا.</p></div>'}
function modal(t,b){$('#mt').textContent=t;$('#mb').innerHTML=b;$('#modal').classList.add('open')}function closeModal(){$('#modal').classList.remove('open')}
(async()=>{const token=localStorage.getItem('lf_admin_token');if(token){await showApp()}else{showLogin()}})()
