/* Naya: collect an outfit, then generate one daily image. */
(()=>{'use strict';
 const chosen=new Map(),$=s=>document.querySelector(s);let state={},busy=false,timer=null,imageObject=null,lastFocus=null,account=null;
 const catalog=()=>typeof products!=='undefined'?products:[];
 const images=p=>p.images?.length?p.images:(p.mainImages||[]).concat(p.subImages||[]).filter(Boolean);
 const token=()=>typeof lfToken==='function'?lfToken():localStorage.getItem('lf_token');
 const base=()=>String(window.LF_API_URL||location.origin).replace(/\/$/,'');
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const safe=s=>typeof s==='string'&&(/^(https?:\/\/|\/(?!\/)|data:image\/(png|jpeg|webp);base64,)/i.test(s)||/^[\w/-]+\.(png|jpe?g|webp)$/i.test(s))&&!/[<>"'\x00-\x20]/.test(s)?s:'';
 async function api(route,options={}){const r=await fetch(base()+'/api/ai/outfit'+route,{...options,headers:{Authorization:'Bearer '+(token()||''),'Content-Type':'application/json',...options.headers},cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||'تعذر الاتصال؛ حاولي لاحقًا.');return d}
 function ensure(){if($('#nayaOutfit'))return;const m=document.createElement('div');m.id='nayaOutfit';m.hidden=true;m.innerHTML=`<div class="no-backdrop" data-no-close></div><section class="no-sheet" role="dialog" aria-modal="true" aria-labelledby="noTitle"><header><div><small>نايا • إطلالتك</small><h2 id="noTitle">جهّزي إطلالة كاملة</h2></div><button data-no-close aria-label="إغلاق">×</button></header><p>اختاري القطع اللي بتحبّي تشوفيها مع بعض، وراجعيها قبل التأكيد. إلك صورة واحدة مجانية باليوم.</p><p class="no-note">اختاري قطعًا متناسقة بتنلبس مع بعض، مثل بلوزة وتنورة وشنطة؛ مش عدة فساتين. الصورة تقريبية وقد تختلف تفاصيل المنتج، ولا تضمن المقاس.</p><div id="noStatus" role="status" aria-live="polite"></div><div id="noResult" hidden><img id="noResultImage" alt="صورة إطلالتك المولدة على نايا"><a id="noDownload" download="naya-outfit.png">حفظ الصورة</a></div><h3>اختياراتك <span id="noCount"></span></h3><div id="noChosen"></div><label class="no-search">إضافة قطعة للإطلالة<input id="noSearch" type="search" placeholder="ابحثي عن ملابس أو إكسسوارات" autocomplete="off"></label><div id="noCatalog"></div><footer><button id="noReview">راجعي الإطلالة</button><div id="noConfirm" hidden><p>هل انتهيتِ من اختيار كل القطع؟ تُحتسب صورتك اليومية بعد نجاح التوليد فقط.</p><button id="noGenerate">أكّدي وولّدي الصورة</button><button id="noBack">تعديل الاختيارات</button></div></footer></section>`;document.body.appendChild(m);
 $('#noSearch').addEventListener('input',renderCatalog);$('#noReview').onclick=()=>{if(!chosen.size)return message('اختاري قطعة واحدة على الأقل.');$('#noConfirm').hidden=false;$('#noReview').hidden=true;$('#noConfirm').scrollIntoView({block:'nearest'})};$('#noBack').onclick=edit;$('#noGenerate').onclick=generate;
 m.addEventListener('click',e=>{if(e.target.closest('[data-no-close]'))close();const a=e.target.closest('[data-no-add]'),r=e.target.closest('[data-no-remove]');if(a){const id=Number(a.dataset.noAdd);if(chosen.size>=5&&!chosen.has(id))return message('يمكنك جمع حتى خمس قطع متناسقة.');chosen.set(id,{productId:id,imageIndex:0});edit();render()}if(r){chosen.delete(Number(r.dataset.noRemove));edit();render()}});
 m.addEventListener('change',e=>{if(e.target.matches('[data-no-image]')){chosen.get(Number(e.target.dataset.noImage)).imageIndex=Number(e.target.value);edit();renderChosen()}});
 }
 function message(text){$('#noStatus').textContent=text}
 function edit(){$('#noConfirm').hidden=true;$('#noReview').hidden=false}
 function renderChosen(){$('#noCount').textContent='('+chosen.size+'/5)';$('#noChosen').innerHTML=Array.from(chosen.values()).map(item=>{const p=catalog().find(x=>Number(x.id)===item.productId);if(!p)return'';const pics=images(p);return `<div class="no-item"><img src="${esc(safe(pics[item.imageIndex]))}" alt=""><div><b>${esc(p.name)}</b>${pics.length>1?`<label>صورة القطعة أو اللون<select data-no-image="${item.productId}">${pics.map((_,i)=>`<option value="${i}" ${i===item.imageIndex?'selected':''}>الصورة ${i+1}</option>`).join('')}</select></label>`:''}</div><button data-no-remove="${item.productId}" aria-label="حذف ${esc(p.name)}">×</button></div>`}).join('')||'<p>لسه ما اخترتِ قطعًا.</p>'}
 function eligible(p){return /ملابس|فستان|بلوز|قميص|تنور|بنطلون|جاكيت|شنط|حقيبة|اكسسوار|إكسسوار|ساعة|حلق|نظار|dress|shirt|skirt|pants|jacket|bag|watch|accessor|earring|glasses/i.test([p.name,p.cat,p.category].join(' '))}
 function renderCatalog(){const q=($('#noSearch').value||'').trim().toLowerCase();$('#noCatalog').innerHTML=catalog().filter(p=>eligible(p)&&images(p).length&&(!q||[p.name,p.cat,p.category].join(' ').toLowerCase().includes(q))).slice(0,40).map(p=>`<button class="no-product" data-no-add="${Number(p.id)}"><img loading="lazy" src="${esc(safe(images(p)[0]))}" alt=""><span>${esc(p.name)}</span><small>${chosen.has(Number(p.id))?'مضافة ✓':'أضيفي للإطلالة +'}</small></button>`).join('')||'<p>لا توجد قطع مطابقة.</p>'}
 function render(){renderChosen();renderCatalog();$('#noReview').disabled=busy||!chosen.size||!state.enabled||['pending','complete'].includes(state.state);$('#noGenerate').disabled=$('#noReview').disabled;$('#noSearch').disabled=busy;}
 async function showImage(day){const r=await fetch(base()+'/api/ai/outfit/image?day='+encodeURIComponent(day),{headers:{Authorization:'Bearer '+token()},cache:'no-store'});if(!r.ok)throw new Error('تعذر تحميل الصورة المحفوظة.');const b=await r.blob();if(imageObject)URL.revokeObjectURL(imageObject);imageObject=URL.createObjectURL(b);$('#noResultImage').src=imageObject;$('#noDownload').href=imageObject;$('#noResult').hidden=false}
 async function refresh(){const current=token();if(account!==current){if(account!==null)chosen.clear();account=current;busy=false;state={};$('#noResult').hidden=true;if(imageObject){URL.revokeObjectURL(imageObject);imageObject=null}}if(!current){state={enabled:false};message('سجّلي الدخول من «حسابي» لحفظ صورتك المجانية اليومية، ثم افتحي الإطلالة.');render();return}try{state=await api('/status');busy=state.state==='pending';render();if(state.state==='complete'){message('صورتك جاهزة ومحفوظة. صورتك المجانية التالية بعد منتصف الليل بتوقيت فلسطين.');await showImage(state.day)}else if(busy){message('نايا بتجهّز إطلالتك… يمكنك إغلاق النافذة والرجوع للنتيجة.');poll()}else message(!state.enabled?'تجهيز الإطلالة متاح؛ توليد الصور لم يُفعّل بعد.':state.message||'إلك صورة مجانية اليوم. اجمعي كل القطع قبل التأكيد.')}catch(e){message(e.message)}}
 function poll(){clearTimeout(timer);if(!$('#nayaOutfit').hidden)timer=setTimeout(refresh,4000)}
 async function generate(){if(busy)return;busy=true;render();message('جارٍ تأكيد الإطلالة…');try{await api('/generate',{method:'POST',body:JSON.stringify({items:Array.from(chosen.values())})});edit();await refresh()}catch(e){busy=false;message(e.message);render()}}
 function open(p){ensure();lastFocus=document.activeElement;if(p?.id&&eligible(p)&&chosen.size<5&&!chosen.has(Number(p.id)))chosen.set(Number(p.id),{productId:Number(p.id),imageIndex:0});$('#nayaOutfit').hidden=false;document.documentElement.classList.add('no-locked');render();refresh();$('#noSearch').focus()}
 function close(){clearTimeout(timer);$('#nayaOutfit').hidden=true;document.documentElement.classList.remove('no-locked');lastFocus?.focus()}
 document.addEventListener('keydown',e=>{if(!$('#nayaOutfit')||$('#nayaOutfit').hidden)return;if(e.key==='Escape')close();if(e.key==='Tab'){const nodes=Array.from($('#nayaOutfit').querySelectorAll('button,input,select,a[href]')).filter(n=>!n.disabled&&n.getClientRects().length);const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}});
 document.addEventListener('click',e=>{const t=e.target.closest('button,a');if(!t||t.closest('#nayaOutfit'))return;if(/جربيها\s*علي|جرّبيها\s*علي|جهّزي إطلالتك/.test(t.textContent)){e.preventDefault();e.stopImmediatePropagation();const c=t.closest('[data-product-id],[data-id]');const p=c?catalog().find(x=>String(x.id)===String(c.dataset.productId||c.dataset.id)):null;open(p)}},true);
 function entry(){if($('#noEntry'))return;const card=$('#lfStoreAiCard');if(card){const b=document.createElement('button');b.id='noEntry';b.className='lf-store-ai-open';b.textContent='جهّزي إطلالتك';b.onclick=()=>open();card.appendChild(b)}}
 document.addEventListener('DOMContentLoaded',entry);if(document.readyState!=='loading')entry();window.LadiesFirstNayaOutfit={open,close};
})();
